apiVersion: v1
kind: Service
metadata:
  namespace: dev
  annotations:
    app.quarkus.io/quarkus-version: 3.14.4
    app.quarkus.io/build-timestamp: 2024-09-20 - 09:02:03 +0000
  labels:
    app.kubernetes.io/name: helm-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: helm-quickstart
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ HTTP_PORT }}
  selector:
    app.kubernetes.io/name: helm-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
